"""
Django settings for lab1 project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

#Path(__file__) — путь к текущему файлу
#.resolve() — делает путь абсолютным
#.parent.parent — поднимается на 2 уровня вверх (к корню проекта)
#BASE_DIR — корневая папка проекта
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zk6npygkeq0ga-)bir00zdb#-d-7zpp6$x&8=7w8e601gd2e^^'

# SECURITY WARNING: don't run with debug turned on in production!
# Режим отладки — True при разработке, False на сервере. При True показывает подробные ошибки.
DEBUG = True

#Разрешенные хосты — список доменов, где может работать сайт. На разработке пустой
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', #админ-панель
    'django.contrib.auth', #аутентификация 
    'django.contrib.contenttypes', #работа с типами данных 
    'django.contrib.sessions', #сессии пользователей 
    'django.contrib.messages', #сообщения для пользователей
    'django.contrib.staticfiles', #статические файлы
    'mainapp', #наше приложение
    'rest_framework',
]

#промежуточные слои
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', #безопаность
    'django.contrib.sessions.middleware.SessionMiddleware', #сессии 
    'django.middleware.common.CommonMiddleware', #общие функции
    'django.middleware.csrf.CsrfViewMiddleware', #защита от CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', #авторизация
    'django.contrib.messages.middleware.MessageMiddleware', #сообщения
    'django.middleware.clickjacking.XFrameOptionsMiddleware', #защита от clickjacking
]

ROOT_URLCONF = 'lab1.urls' #указывает, какой файл отвечает за маршруты

#настройка html-шаблонов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lab1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'lab1_db',                    
        'USER': 'django',                      
        'PASSWORD': '2NevjFoQisyVaV',        
        'HOST': 'localhost',
        'PORT': '5433',                        
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us' #язык

TIME_ZONE = 'UTC' #часовой пояс 

USE_I18N = True #включить переводы

USE_TZ = True #использовать временные зоны


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
