# Generated by Django 6.0.3 on 2026-03-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('published_date', models.DateField(verbose_name='Published date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is available')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
